import os

from dotenv import load_dotenv

load_dotenv(dotenv_path="secrets.env")

BACKEND_API_KEY = os.getenv("BACKEND_API_KEY")
BACKEND_ORIGINS = ["https://agastya.streamlit.app"]
LOGS_FOLDER_PATH = os.getenv("LOGS_FOLDER_PATH")

DB_CONFIG = {
    "user": os.getenv("DB_USERNAME"),
    "password": os.getenv("DB_PASSWORD"),
    "host": os.getenv("DB_HOST"),
    "database": os.getenv("DB_NAME")
}

STUDENT_PROFILES_FILE_PATH = os.getenv("STUDENT_PROFILES_FILE_PATH")
STUDENT_NARRATIVES_BUCKET_NAME = os.getenv("STUDENT_NARRATIVES_BUCKET_NAME")
STUDENT_NARRATIVES_BUCKET_PREFIX = os.getenv("STUDENT_NARRATIVES_BUCKET_PREFIX")

MAX_DOCS_TO_RETRIEVE = int(os.getenv("RAG_MAX_DOC_RETRIEVE"))

if MAX_DOCS_TO_RETRIEVE < 1:
    MAX_DOCS_TO_RETRIEVE = 4

TEMPORARY_VECTORSTORES_DIRECTORY = os.getenv("TEMPORARY_VECTORSTORES_DIRECTORY")

DOCUMENT_EMBEDDING_MODEL_ID = os.getenv("DOCUMENT_EMBEDDING_MODEL_ID")

RESPONSE_GENERATION_MODEL_ID = os.getenv("RESPONSE_GENERATION_MODEL_ID")

RESPONSE_GENERATION_MODEL_TEMPERATURE = float(os.getenv("RESPONSE_GENERATION_MODEL_TEMPERATURE"))

RESPONSE_GENERATION_MODEL_MAX_TOKENS = int(os.getenv("RESPONSE_GENERATION_MODEL_MAX_TOKENS"))