name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to repository directory
            cd /home/ubuntu/app
            
            # Store current git hash to compare later
            OLD_COMMIT=$(git rev-parse HEAD)
            
            # Pull latest changes
            git pull origin main
            
            # If code has changed, update dependencies and restart services
            if [ "$OLD_COMMIT" != "$(git rev-parse HEAD)" ]; then
              # Activate virtual environment
              source venv/bin/activate
              
              # Update dependencies only if requirements.txt has changed
              if git diff --name-only $OLD_COMMIT HEAD | grep -q "requirements.txt"; then
                pip install -r requirements.txt
              fi
              
              # Restart services
              sudo systemctl restart fastapi streamlit
              
              echo "Deployment completed successfully on $(date)"
            else
              echo "No changes detected. Skipping deployment."
            fi