[theme]
primaryColor = "#D4A373"
backgroundColor = "#FAF3E0"
secondaryBackgroundColor = "#E8D7B3"
textColor = "#4A4A4A"
font = "serif"

[server]
runOnSave=true

[runner]
fastReruns = true

[client]
showSidebarNavigation = false